export const categories = [
  { id: 1, name: "Clothing", slug: "clothing" },
  { id: 2, name: "Shoes", slug: "shoes" },
  { id: 3, name: "Accessories", slug: "accessories" },
  { id: 4, name: "Electronics", slug: "electronics" },
  { id: 5, name: "Home & Kitchen", slug: "home-kitchen" },
  { id: 6, name: "Beauty", slug: "beauty" },
]

export const products = [
  {
    id: "1",
    name: "Premium Cotton T-Shirt",
    description: "Soft and comfortable cotton t-shirt with a modern fit.",
    price: 29.99,
    discountPercentage: 0,
    rating: 4.5,
    reviewCount: 128,
    category: "Clothing",
    featured: true,
    createdAt: "2023-12-15",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["#000000", "#FFFFFF", "#6B7280", "#EF4444"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "2",
    name: "Wireless Bluetooth Headphones",
    description: "High-quality sound with noise cancellation technology.",
    price: 199.99,
    discountPercentage: 15,
    rating: 4.8,
    reviewCount: 256,
    category: "Electronics",
    featured: true,
    createdAt: "2024-01-10",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["#000000", "#FFFFFF", "#3B82F6"],
  },
  {
    id: "3",
    name: "Leather Crossbody Bag",
    description: "Stylish and practical leather bag with adjustable strap.",
    price: 79.99,
    discountPercentage: 0,
    rating: 4.3,
    reviewCount: 89,
    category: "Accessories",
    featured: false,
    createdAt: "2024-02-05",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["#78350F", "#000000", "#D1D5DB"],
  },
  {
    id: "4",
    name: "Smart Fitness Watch",
    description: "Track your fitness goals with this advanced smartwatch.",
    price: 149.99,
    discountPercentage: 10,
    rating: 4.6,
    reviewCount: 175,
    category: "Electronics",
    featured: true,
    createdAt: "2024-03-01",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["#000000", "#3B82F6", "#EF4444"],
  },
  {
    id: "5",
    name: "Slim Fit Jeans",
    description: "Classic denim jeans with a modern slim fit design.",
    price: 59.99,
    discountPercentage: 0,
    rating: 4.2,
    reviewCount: 112,
    category: "Clothing",
    featured: false,
    createdAt: "2024-01-25",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["#1F2937", "#6B7280", "#78350F"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "6",
    name: "Stainless Steel Water Bottle",
    description: "Eco-friendly water bottle that keeps drinks cold for 24 hours.",
    price: 24.99,
    discountPercentage: 20,
    rating: 4.7,
    reviewCount: 203,
    category: "Home & Kitchen",
    featured: false,
    createdAt: "2023-11-20",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["#000000", "#3B82F6", "#EF4444", "#10B981"],
  },
  {
    id: "7",
    name: "Wireless Charging Pad",
    description: "Fast wireless charging for all Qi-enabled devices.",
    price: 39.99,
    discountPercentage: 0,
    rating: 4.4,
    reviewCount: 87,
    category: "Electronics",
    featured: false,
    createdAt: "2024-02-15",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "8",
    name: "Running Shoes",
    description: "Lightweight and comfortable shoes for running and training.",
    price: 89.99,
    discountPercentage: 15,
    rating: 4.5,
    reviewCount: 156,
    category: "Shoes",
    featured: true,
    createdAt: "2024-03-10",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["#000000", "#3B82F6", "#EF4444", "#10B981"],
    sizes: ["7", "8", "9", "10", "11", "12"],
  },
  {
    id: "9",
    name: "Ceramic Coffee Mug",
    description: "Elegant ceramic mug for your morning coffee or tea.",
    price: 14.99,
    discountPercentage: 0,
    rating: 4.3,
    reviewCount: 92,
    category: "Home & Kitchen",
    featured: false,
    createdAt: "2023-12-05",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["#FFFFFF", "#000000", "#6B7280", "#EF4444"],
  },
  {
    id: "10",
    name: "Moisturizing Face Cream",
    description: "Hydrating face cream for all skin types.",
    price: 34.99,
    discountPercentage: 10,
    rating: 4.6,
    reviewCount: 118,
    category: "Beauty",
    featured: false,
    createdAt: "2024-01-15",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
  },
  {
    id: "11",
    name: "Leather Wallet",
    description: "Genuine leather wallet with multiple card slots.",
    price: 49.99,
    discountPercentage: 0,
    rating: 4.4,
    reviewCount: 76,
    category: "Accessories",
    featured: false,
    createdAt: "2023-11-10",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["#78350F", "#000000"],
  },
  {
    id: "12",
    name: "Portable Bluetooth Speaker",
    description: "Compact speaker with powerful sound for on-the-go music.",
    price: 69.99,
    discountPercentage: 20,
    rating: 4.7,
    reviewCount: 143,
    category: "Electronics",
    featured: false,
    createdAt: "2024-02-20",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["#000000", "#3B82F6", "#EF4444"],
  },
]
